// <auto-generated />
using System;
using GaraMan.GaraDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GaraMan.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240801060951_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GaraMan.Models.Dichvu385", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Cost")
                        .HasColumnType("real");

                    b.Property<string>("Dichvuyeucau385id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phutungyeucau385id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Dichvuyeucau385id");

                    b.HasIndex("Phutungyeucau385id");

                    b.ToTable("Dichvus");
                });

            modelBuilder.Entity("GaraMan.Models.Dichvuyeucau385", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("nhanvienKTId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("nhanvienKTId");

                    b.ToTable("Dichvuyeucaus");
                });

            modelBuilder.Entity("GaraMan.Models.Hoadon385", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("dichvuyeucauid")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("khId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nvbhId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("phutungyeucauid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("total")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.HasIndex("dichvuyeucauid");

                    b.HasIndex("khId");

                    b.HasIndex("nvbhId");

                    b.HasIndex("phutungyeucauid");

                    b.ToTable("Hoadons");
                });

            modelBuilder.Entity("GaraMan.Models.Hoadonnhap385", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NhacungcapId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NhanvienkhoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("total")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.HasIndex("NhacungcapId");

                    b.HasIndex("NhanvienkhoId");

                    b.ToTable("Hoadonnhaps");
                });

            modelBuilder.Entity("GaraMan.Models.Lichhen385", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KhachhangId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("KhachhangId");

                    b.ToTable("Lichhens");
                });

            modelBuilder.Entity("GaraMan.Models.Nhacungcap385", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Nhacungcaps");
                });

            modelBuilder.Entity("GaraMan.Models.Phutung385", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Cost")
                        .HasColumnType("real");

                    b.Property<string>("HoadonnhapId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HoadonnhapId");

                    b.ToTable("Phutungs");
                });

            modelBuilder.Entity("GaraMan.Models.Phutungyeucau385", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Phutungyeucaus");
                });

            modelBuilder.Entity("GaraMan.Models.Thanhvien385", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Thanhviens");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Thanhvien385");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GaraMan.Models.Khachhang385", b =>
                {
                    b.HasBaseType("GaraMan.Models.Thanhvien385");

                    b.Property<string>("note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Khachhang385");
                });

            modelBuilder.Entity("GaraMan.Models.Nhanvien385", b =>
                {
                    b.HasBaseType("GaraMan.Models.Thanhvien385");

                    b.Property<string>("chucvu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Nhanvien385");
                });

            modelBuilder.Entity("GaraMan.Models.NhanvienKT385", b =>
                {
                    b.HasBaseType("GaraMan.Models.Nhanvien385");

                    b.HasDiscriminator().HasValue("NhanvienKT385");
                });

            modelBuilder.Entity("GaraMan.Models.Nhanvienbanhang385", b =>
                {
                    b.HasBaseType("GaraMan.Models.Nhanvien385");

                    b.HasDiscriminator().HasValue("Nhanvienbanhang385");
                });

            modelBuilder.Entity("GaraMan.Models.Nhanvienkho385", b =>
                {
                    b.HasBaseType("GaraMan.Models.Nhanvien385");

                    b.HasDiscriminator().HasValue("Nhanvienkho385");
                });

            modelBuilder.Entity("GaraMan.Models.Nhanvienquanly385", b =>
                {
                    b.HasBaseType("GaraMan.Models.Nhanvien385");

                    b.HasDiscriminator().HasValue("Nhanvienquanly385");
                });

            modelBuilder.Entity("GaraMan.Models.Dichvu385", b =>
                {
                    b.HasOne("GaraMan.Models.Dichvuyeucau385", null)
                        .WithMany("ListDV")
                        .HasForeignKey("Dichvuyeucau385id");

                    b.HasOne("GaraMan.Models.Phutungyeucau385", null)
                        .WithMany("ListDV")
                        .HasForeignKey("Phutungyeucau385id");
                });

            modelBuilder.Entity("GaraMan.Models.Dichvuyeucau385", b =>
                {
                    b.HasOne("GaraMan.Models.NhanvienKT385", "nhanvienKT")
                        .WithMany()
                        .HasForeignKey("nhanvienKTId");

                    b.Navigation("nhanvienKT");
                });

            modelBuilder.Entity("GaraMan.Models.Hoadon385", b =>
                {
                    b.HasOne("GaraMan.Models.Dichvuyeucau385", "dichvuyeucau")
                        .WithMany()
                        .HasForeignKey("dichvuyeucauid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GaraMan.Models.Khachhang385", "kh")
                        .WithMany()
                        .HasForeignKey("khId");

                    b.HasOne("GaraMan.Models.Nhanvienbanhang385", "nvbh")
                        .WithMany()
                        .HasForeignKey("nvbhId");

                    b.HasOne("GaraMan.Models.Phutungyeucau385", "phutungyeucau")
                        .WithMany()
                        .HasForeignKey("phutungyeucauid");

                    b.Navigation("dichvuyeucau");

                    b.Navigation("kh");

                    b.Navigation("nvbh");

                    b.Navigation("phutungyeucau");
                });

            modelBuilder.Entity("GaraMan.Models.Hoadonnhap385", b =>
                {
                    b.HasOne("GaraMan.Models.Nhacungcap385", "nhacungcap")
                        .WithMany()
                        .HasForeignKey("NhacungcapId");

                    b.HasOne("GaraMan.Models.Nhanvienkho385", "nhanvienkho")
                        .WithMany()
                        .HasForeignKey("NhanvienkhoId");

                    b.Navigation("nhacungcap");

                    b.Navigation("nhanvienkho");
                });

            modelBuilder.Entity("GaraMan.Models.Lichhen385", b =>
                {
                    b.HasOne("GaraMan.Models.Khachhang385", "Khachhang")
                        .WithMany()
                        .HasForeignKey("KhachhangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khachhang");
                });

            modelBuilder.Entity("GaraMan.Models.Phutung385", b =>
                {
                    b.HasOne("GaraMan.Models.Hoadonnhap385", null)
                        .WithMany("ListPhutung")
                        .HasForeignKey("HoadonnhapId");
                });

            modelBuilder.Entity("GaraMan.Models.Dichvuyeucau385", b =>
                {
                    b.Navigation("ListDV");
                });

            modelBuilder.Entity("GaraMan.Models.Hoadonnhap385", b =>
                {
                    b.Navigation("ListPhutung");
                });

            modelBuilder.Entity("GaraMan.Models.Phutungyeucau385", b =>
                {
                    b.Navigation("ListDV");
                });
#pragma warning restore 612, 618
        }
    }
}
